version: "3.2"
services:
  react-app:
    container_name: kuma.germaniii.com
    build:
      context: ./root
      dockerfile: ../infra/docker/Dockerfile
    ports:
      - 8007:5173
    volumes:
      - ./root:/app
      - ../../infra/.env:/.env.local
      - /app/dist
      - /app/node_modules
