version: "3.2"
services:
  react-app:
    container_name: kuma.germaniii.com
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8007:5173
    volumes:
      - ./:/app
      - /app/dist
      - /app/node_modules
