name: Validate Pull Request Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Docker Build
        run: |
          docker build --file Dockerfile.prod -t test-image .
