name: Deploy

on:
  registry_package:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull and Run Container
        run: |
            echo "[+] Stopping old container"
            docker stop kuma.germaniii.com || true
            docker rm kuma.germaniii.com || true

            echo "[+] Pulling latest image"
            docker pull ${{ vars.BASE_URL }}/${{ vars.USER }}/kuma.germaniii.com:latest

            echo "[+] Running new container"
            docker run -d \
              --name kuma.germaniii.com \
              -p 8004:80 \
              --restart unless-stopped \
              ${{ vars.BASE_URL }}/${{ vars.USER }}/kuma.germaniii.com:latest
