name: Deploy to VPS

on:
  registry_package:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "[+] Logging in to container registry"
            echo "${{ secrets.PAT }}" | docker login ${{ vars.BASE_URL }} -u ${{ vars.USER }} --password-stdin

            echo "[+] Stopping old container"
            docker stop kuma.germaniii.com || true
            docker rm kuma.germaniii.com || true

            echo "[+] Pulling latest image"
            docker pull ${{ vars.BASE_URL }}/${{ vars.USER }}/kuma.germaniii.com:latest

            echo "[+] Running new container"
            docker run -d \
              --name kuma.germaniii.com \
              -p 8007:80 \
              --restart unless-stopped \
              ${{ vars.BASE_URL }}/${{ vars.USER }}/kuma.germaniii.com:latest

