name: Update Main Repo on Push

on:
  push:
    branches:
      - master

jobs:
  update-submodule-on-main-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # Ensure submodules are initialized

      - name: Configure Git
        run: |
          git config --global user.name "gitea-bot"
          git config --global user.email "bot@example.com"

      - name: Clone Main Repo and Update Submodule
        env:
          TOKEN: ${{ vars.PAT }}
          USER: ${{ vars.USER }}
          BASE_URL: ${{ vars.BASE_URL }}
          MAIN_REPO: ${{ vars.MAIN_REPO }}
        run: |
          git clone http://${USER}:${TOKEN}@${BASE_URL}/${USER}/${MAIN_REPO}.git
          cd ${MAIN_REPO}
          git submodule update --remote kuma.germaniii.com
          git add kuma.germaniii.com
          git commit -m "ci: update kuma.germaniii.com to latest $(date --iso-8601=seconds)" || echo "No changes"
          git push origin master

