/** Curated VS Code color keys per popular theme (subset for app tokens). */
export const THEME_PRESETS = [
  {
    id: 'dark-plus',
    label: 'Dark+',
    type: 'dark',
    colors: {
      'editor.background': '#1e1e1e',
      'editor.foreground': '#d4d4d4',
      'sideBar.background': '#252526',
      'editorGroup.border': '#3c3c3c',
      'focusBorder': '#007acc',
      'button.background': '#007acc',
      'descriptionForeground': '#858585',
      'input.background': '#3c3c3c',
      'errorForeground': '#f48771',
      'terminal.ansiGreen': '#4ec9b0',
      'terminal.ansiRed': '#f48771',
      'editor.selectionBackground': '#264f78',
    },
  },
  {
    id: 'light-plus',
    label: 'Light+',
    type: 'light',
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#000000',
      'sideBar.background': '#f3f3f3',
      'editorGroup.border': '#e5e5e5',
      'focusBorder': '#007acc',
      'button.background': '#007acc',
      'descriptionForeground': '#717171',
      'input.background': '#ffffff',
      'errorForeground': '#cd3131',
      'terminal.ansiGreen': '#008000',
      'terminal.ansiRed': '#cd3131',
      'editor.selectionBackground': '#add6ff',
    },
  },
  {
    id: 'one-dark',
    label: 'One Dark',
    type: 'dark',
    colors: {
      'editor.background': '#282c34',
      'editor.foreground': '#abb2bf',
      'sideBar.background': '#21252b',
      'editorGroup.border': '#181a1f',
      'focusBorder': '#528bff',
      'button.background': '#528bff',
      'descriptionForeground': '#5c6370',
      'input.background': '#1d1f23',
      'errorForeground': '#e06c75',
      'terminal.ansiGreen': '#98c379',
      'terminal.ansiRed': '#e06c75',
      'editor.selectionBackground': '#3e4451',
    },
  },
  {
    id: 'dracula',
    label: 'Dracula',
    type: 'dark',
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'sideBar.background': '#21222c',
      'editorGroup.border': '#44475a',
      'focusBorder': '#bd93f9',
      'button.background': '#bd93f9',
      'descriptionForeground': '#6272a4',
      'input.background': '#44475a',
      'errorForeground': '#ff5555',
      'terminal.ansiGreen': '#50fa7b',
      'terminal.ansiRed': '#ff5555',
      'editor.selectionBackground': '#44475a',
    },
  },
  {
    id: 'monokai',
    label: 'Monokai',
    type: 'dark',
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#f8f8f2',
      'sideBar.background': '#1e1f1c',
      'editorGroup.border': '#49483e',
      'focusBorder': '#a6e22e',
      'button.background': '#a6e22e',
      'descriptionForeground': '#75715e',
      'input.background': '#3e3d32',
      'errorForeground': '#f92672',
      'terminal.ansiGreen': '#a6e22e',
      'terminal.ansiRed': '#f92672',
      'editor.selectionBackground': '#49483e',
    },
  },
  {
    id: 'solarized-dark',
    label: 'Solarized Dark',
    type: 'dark',
    colors: {
      'editor.background': '#002b36',
      'editor.foreground': '#839496',
      'sideBar.background': '#073642',
      'editorGroup.border': '#073642',
      'focusBorder': '#268bd2',
      'button.background': '#268bd2',
      'descriptionForeground': '#586e75',
      'input.background': '#073642',
      'errorForeground': '#dc322f',
      'terminal.ansiGreen': '#859900',
      'terminal.ansiRed': '#dc322f',
      'editor.selectionBackground': '#073642',
    },
  },
  {
    id: 'github-dark',
    label: 'GitHub Dark',
    type: 'dark',
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#c9d1d9',
      'sideBar.background': '#010409',
      'editorGroup.border': '#30363d',
      'focusBorder': '#1f6feb',
      'button.background': '#1f6feb',
      'descriptionForeground': '#8b949e',
      'input.background': '#161b22',
      'errorForeground': '#f85149',
      'terminal.ansiGreen': '#3fb950',
      'terminal.ansiRed': '#f85149',
      'editor.selectionBackground': '#264f78',
    },
  },
];

export const getPresetById = (id) =>
  THEME_PRESETS.find((p) => p.id === id) ?? THEME_PRESETS[0];
